modmap:
  - name: capslock
    remap:
      Capslock:
        held: Ctrl
        alone: C-Shift-Space
        alone_timeout_millis: 1000
keymap:
  - name: super
    remap:
      Super-c: C-c
      Super-v: C-v
      Super-a: C-a
